Add Node types to compilation
### Why?

In 99d93fe we explicitly added `jest` to the list of `types`, but this meant
that Node types went missing and tests started failing.

```
    src/searching/search.spec.ts:8:26 - error TS2307: Cannot find module 'node:fs/promises' or its corresponding type declarations.
    src/searching/search.spec.ts:9:18 - error TS2307: Cannot find module 'node:path' or its corresponding type declarations.
    src/searching/search.spec.ts:72:36 - error TS2304: Cannot find name '__dirname'.
    src/searching/downloadTable.spec.ts:17:20 - error TS2304: Cannot find name 'global'.
```

### What?

* add `node` to list of `types`