Updated imports of `webpack-merge`
### Why?

The import structure changed in the latest version.

```
[webpack-cli] Failed to load '/home/leigh/code/touch-pricker/config/webpack.config.dev.js' config
[webpack-cli] TypeError: merge is not a function
```

This should have been changed in 3980f60