Revert "Remove codecov token"
This reverts commit f83d5d32049011888f2306984c60de46c82d83d7.

### Why?

```
There was an error running the uploader:
  Error uploading to https://codecov.io:
    Error: There was an error fetching the storage URL during POST:
      Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.
```